#ifndef H_OBJ_VIEWER
#define H_OBJ_VIEWER

#define OBJ_VIEWER_WINDOW_WIDTH 1000
#define OBJ_VIEWER_WINDOW_HEIGHT 1000 

#define OBJ_VIEWER_VIEWPORT_WIDTH OBJ_VIEWER_WINDOW_WIDTH
#define OBJ_VIEWER_VIEWPORT_HEIGHT OBJ_VIEWER_WINDOW_HEIGHT

#define OBJ_VIEWER_CAMERA_MOVEMENT_COEF 0.1
#define OBJ_VIEWER_CAMERA_MOUSE_SENSITIVITY 0.1

#endif
